import type { ColDef } from 'ag-grid-community';

/**
 * A ColDef generated by buildColumnDefs(), carrying a pointer back to the
 * attribute it was generated from. Consuming apps that need further
 * app-specific fields (e.g. a widget id) should extend this interface in
 * their own codebase rather than the library adding app-specific fields
 * here.
 */
export interface MetadataColDef extends ColDef {
  /** The exact attributeName this column was generated from. */
  sourceAttributeName: string;
}
